### ISSUE TITLE
Crystal json testdata

### ISSUE THREAD

**Issue by sagitta42** [legend-exp/legend-testdata#13]
There is one issue in creating a test metadata file in relation to how LegendGeSim interacts with it: when a detector is simulated, the name of the crystal file corresponding to it is constructed as detector name - slice e.g. detector "V04545A" corresponds to crystal file "V04545.json". The name of the json is currently constructed by looking up the `"name"` field in detector metadata, and removing the slice part, then looking for such a file in a path to crystal metadata directory provided in input settings.

If I want to create a crystal metadata file corresponding to the Public Inverted Coax, as it currently is, the name of the json to be looked up will be "Public Inverted Coa.json" :)

So either we should change the name in the Public Inverted Coax json to be something of LEGEND format e.g. `"name": "VNNXXXS"`, and then create a crystal file `"VNNXXX.json"`, or change something else in such a way that by starting from `invcoax-metadata.json` we can find the corresponding crystal. For example, I could construct the crystal name as type + order + crystal rather than just removing slice from detector name, then Public ICPC would have a crystal `V00000.json` based on its detector json.

**Comment by oschulz** [comment]
Our current dummy detector metadata is here: https://github.com/legend-exp/legend-testdata/tree/main/data/legend/metadata/hardware/detectors/germanium/diodes

Those detectors have names that fit the usual LEGEND naming scheme.

**Comment by sagitta42** [comment]
Thanks! Added files corresponding to the ICPC and the BEGe example files that are also used in LegendGeSim tests #14
